export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAILD = "REGISTER_USER_FAILD"

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILD = "LOGIN_USER_FAILD"

export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAILD = "GET_USER_FAILD"

export const FORGOT_USER_REQUEST = "FORGOT_USER_REQUEST"
export const FORGOT_USER_SUCCESS = "FORGOT_USER_SUCCESS"
export const FORGOT_USER_FAILD = "FORGOT_USER_FAILD"

export const RESET_USER_REQUEST = "RESET_USER_REQUEST"
export const RESET_USER_SUCCESS = "RESET_USER_SUCCESS"
export const RESET_USER_FAILD = "RESET_USER_FAILD"

export const  LOGOUT = "LOGOUT"